// import './jsx/create-react-element'
// import './jsx/jsx-basic-1'
// import './component-basic/props-basic-1'
// import './component-basic/props-children'
// import './component-basic/function-component'
//  import './component-intermediate/state-study'
// import './component-intermediate/set-state-caveat/'
// import './component-intermediate/counter-demo'
// import './component-intermediate/shallow-merge-caveat/'
// import './component-intermediate/manipulate-list'
// import './component-intermediate/todo-app-demo'
// import './component-intermediate/lifecycle-methods'
// import './component-intermediate/timer-demo'
//  import './component-intermediate/lifecycle-method-should-component-update'
// import './component-intermediate/force-update-demo'

// import './component-advanced/ref-demo'
// import './component-advanced/controlled-component'
import './component-advanced/reservation-form'


