// import './jsx/create-react-element'
// import './jsx/jsx-basic-1'
// import './component-basic/props-basic-1'
// import './component-basic/props-children'
// import './component-basic/function-component'
//  import './component-intermediate/state-study'
// import './component-intermediate/set-state-caveat/'
// import './component-intermediate/counter-demo'
// import './component-intermediate/shallow-merge-caveat/'
import './component-intermediate/manipulate-list'